# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
default-template: new-template
system-ghc: true
allow-newer: true
templates:
  scm-init: git
  ghc-options:
    "$everything": -haddock
  params:
    author-name: DRAGOON8192
    author-email: dragoon8192@gmail.com
    github-username: dragoon8192
#    copyright:
